// @ts-ignore - resolved via allowJs; types in ../../website/Package/index.d.ts
import { init } from '../../website/Package/index.js';
import type { Exports } from '../../website/Package/bridge-js.js';
// `renderGraphDark` is generated by `build.sh` but the typed Exports may lag
// until the next build — widen locally so this file compiles regardless.
type ExportsWithDark = Exports & { renderGraphDark?: (vgl: string) => string };

export type RenderVGL = (vgl: string, darkMode?: boolean) => string;
// @ts-ignore - esbuild's binary loader turns this into a Uint8Array
import wasmBinary from '../VGraphWasm.wasm';

declare global {
    interface Window {
        graphvizLayout: (dot: string, engine?: string, format?: string) => string;
        graphvizLayoutJSON: (dot: string, engine?: string) => unknown;
    }
}

async function loadGraphviz(): Promise<void> {
    // Dynamic URL import — works in Electron's renderer without bundling the ~10 MB library.
    // @ts-ignore
    const { Graphviz } = await import('https://cdn.jsdelivr.net/npm/@hpcc-js/wasm-graphviz@1.21.5/dist/index.js');
    const graphviz = await Graphviz.load();

    window.graphvizLayout = (dot, engine = 'dot', format = 'svg') =>
        graphviz.layout(dot, format, engine);
    window.graphvizLayoutJSON = (dot, engine = 'dot') =>
        JSON.parse(graphviz.layout(dot, 'json', engine));
}

export async function initVithanco(): Promise<RenderVGL> {
    await loadGraphviz();

    // The WASM binary is embedded at build time (esbuild binary loader),
    // so init() never executes the import.meta.url fetch in Package/index.js.
    const { exports }: { exports: ExportsWithDark } = await init({
        module: wasmBinary,
        getImports: () => ({}),
    });

    return (vgl: string, darkMode = false): string => {
        const result =
            darkMode && typeof exports.renderGraphDark === 'function'
                ? exports.renderGraphDark(vgl)
                : exports.renderGraph(vgl);
        // renderGraph embeds errors as SVG text elements; surface them as real errors.
        if (result.includes('Error:') && result.includes('<text')) {
            const match = result.match(/Error:([^<]+)/);
            throw new Error(match ? match[1].trim() : 'Rendering failed');
        }
        return result;
    };
}
